name: flitt_mobile
description: Flitt SDK for Mobile(Android, iOS). The only way to accept payment with Fondy service on Flutter platform for mobiles.
version: 1.0.1
homepage: https://github.com/flittpayments/flutter
repository: https://github.com/flittpayments/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ">=2.0.10 <5.0.0"
  http: ">=0.13.3 <2.0.0"
  email_validator: ">=2.0.1 <3.0.0"

  url_launcher: ">=6.1.11 <7.0.0"
  package_info_plus: ">=8.0.0 <9.0.0"


dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.flitt.mobile
        pluginClass: FlittMobilePlugin
      ios:
        pluginClass: FlittMobilePlugin


